import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TChildren } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: TChildren) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <main>{children}</main>
      </body>
    </html>
  );
}
